version: '3'
services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - target
      - pom.xml:pom.xml
      - src/main:/src/main
    stdin_open:
      true
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - target
      - pom.xml:pom.xml
      - src/test:/src/test
    stdin_open:
      true
    command:
      ["java","-jar","junit-platform-console-standalone-1.3.1.jar","TestAddingNumbers.java"]
