language: generic

sudo: required
services:
  - docker
before_install:
  - docker build -t examplenode -f Docker/ExampleNode/Dockerfile.dev .
script:
  - docker run -e CI=true examplenode npm run test