version: '3'
services:
  web:
    image: thegloriousgenesis/cs_learning.web.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open:
      true
#  tests:
#    image: thegloriousgenesis/cs_learning.test.dev
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - /app/node_modules
#      - .:/app
#    command: ["npm","run","test"]

