apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: dev-test-account
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 9376
          volumeMounts:
            - mountPath: /var/run/secrets/tokens # This allows us to mount a token that expires in 2 hours
              name: sa-dev-token
      volumes:
        - name: sa-dev-token
          projected:
            sources:
              - serviceAccountToken: # allows us to config mounted token for sa
                  path: sa-dev-token
                  expirationSeconds: 600
#                  audience: curlsvc # recipient of token must identify themself with and identifier in the list of audience to be validated otherwise reject token
#                  audience: https://kubernetes.default.svc # recipient of token must identify themself with and identifier in the list of audience to be validated otherwise reject token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      serviceAccountName: prod-test-account
      containers:
        - name: my-container
          image: cicirello/pyaction:4.14.0
          command: ["python3", "-m", "http.server", "8000"]
          ports:
            - containerPort: 8000 # The port the container is listening on (for other components in cluster)
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: sa-prod-token
            - mountPath: /etc/get_components
              name: get-component-code
      volumes:
        - name: sa-prod-token
          projected:
            sources:
              - serviceAccountToken:
                  path: sa-prod-token
                  expirationSeconds: 600
        - name: get-component-code
          configMap:
            name: get-components
