apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-test-account
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  namespace: dev
imagePullSecrets: # keeping secrets managed in one place is more secure and also means any container in namespace has access to this secret
  - name: c1eng-docker-local-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-test-account
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  namespace: prod
imagePullSecrets:
  - name: c1eng-docker-local-cred
