apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-test-account
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-test-account
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  namespace: prod
